apiVersion: v1
kind: Service
metadata:
  name: {{ include "digdag.fullname" . }}
  labels:
    {{- include "digdag.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "digdag.selectorLabels" . | nindent 4 }}
